server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.196.175.117:3306/Ivy?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: zhou11
    password: 100686
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis 配置
  redis:
    # 机器ip
    host: 121.196.175.117
    # 端口号6379
    port: 6379
    # 密码
    password: zfb1997JAY
    # 超时时间
    timeout: 10s
    lettuce:
      pool:
        # 最小连接数
        min-idle: 0
        # 最大连接数
        max-idle: 8
        # 最大活跃链接
        max-active: 8
        # 超时时间
        max-wait: -1ms


